version: '3'
services:
  react-simple-todo-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
    # environment:
    #   - PORT=5000
    #   - TOKEN_SECRET=random
    #   - NODE_ENV=development
    #   - POSTGRES_HOST=react-simple-todo-db.cvt6fotfivqu.us-east-1.rds.amazonaws.com
    #   - POSTGRES_PORT=5432
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=ManUtdCarrick1991
    #   - POSTGRES_DB=testtodoreact
    env_file:
      - ./.env