version: '3'
services:
  react-simple-todo-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        REACT_APP_PORT: 80
        REACT_APP_TOKEN_SECRET: random
        REACT_APP_POSTGRES_HOST: 
        REACT_APP_POSTGRES_PORT: 5432
        REACT_APP_POSTGRES_USER: 
        REACT_APP_POSTGRES_PASSWORD: 
        REACT_APP_POSTGRES_DB: 

    ports:
      - "8080:80"
