version: '3'
services:
  react-simple-todo-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        REACT_APP_PORT: 80
        REACT_APP_TOKEN_SECRET: random
        REACT_APP_POSTGRES_HOST: simple-todo-db.cvt6fotfivqu.us-east-1.rds.amazonaws.com
        REACT_APP_POSTGRES_PORT: 5432
        REACT_APP_POSTGRES_USER: postgres
        REACT_APP_POSTGRES_PASSWORD: ManUtdCarrick1991
        REACT_APP_POSTGRES_DB: testtodoreact

    ports:
      - "8080:80"
    # environment:
    #   - PORT=5000
    #   - TOKEN_SECRET=random
    #   - NODE_ENV=development
    #   - POSTGRES_HOST=react-simple-todo-db.cvt6fotfivqu.us-east-1.rds.amazonaws.com
    #   - POSTGRES_PORT=5432
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=ManUtdCarrick1991
    #   - POSTGRES_DB=testtodoreact