version: '3'
services:
  react-simple-todo-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src

    env_file:
      - ./.env